# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

output_dir: eval-results # Not needed

# Model Arguments
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  lora_attn_modules: ["q_proj", "v_proj", "output_proj"]
  apply_lora_to_mlp: True
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16 # usually alpha=2*rank
  lora_dropout: 0.0

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/torchtune/llama3_1_8B/lora_dpo_single_device/epoch_0
  checkpoint_files:
    [
      ft-model-00001-of-00004.safetensors,
      ft-model-00002-of-00004.safetensors,
      ft-model-00003-of-00004.safetensors,
      ft-model-00004-of-00004.safetensors,
    ]
  output_dir: ${output_dir}
  model_type: LLAMA3

# Tokenizer
tokenizer:
  _component_: tokenizer.trust_tokenizer
  path: /tmp/Meta-Llama-3.1-8B-Instruct/original/tokenizer.model
  max_seq_len: 1024 # higher increases memory

# Environment
device: cuda
dtype: bf16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2"]
limit: null
max_seq_length: 4096
batch_size: 8
enable_kv_cache: True

# Quantization specific args
quantizer: null
